version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
